name: Heroku Deployment

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Respository
        uses: actions/checkout@v2

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t registry.heroku.com/smart-data-entry-api/web .
          docker push registry.heroku.com/smart-data-entry-api/web

      - name: Release to Heroku
        run: heroku container:release web --app smart-data-entry-api
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        shell: bash
